### ISSUE TITLE
Error in ibmiotf.device.ParseConfigFile

### ISSUE THREAD

**Issue by xulegaspi** [ibm-watson-iot/iot-python#94]
In version 0.3.2, I get the following error when loading the config file (which was working with version 0.3.1):
```
Traceback (most recent call last):
  File "xxxx.py", line 6, in <module>
    options = ibmiotf.device.ParseConfigFile("./xxxx.conf")
  File "/home/xxxx/workspaces/python/test_env/lib/python3.5/site-packages/ibmiotf/device.py", line 929, in ParseConfigFile
    port = parms.getint(sectionHeader, "port")
  File "/usr/lib/python3.5/configparser.py", line 816, in getint
    fallback=fallback, **kwargs)
  File "/usr/lib/python3.5/configparser.py", line 806, in _get_conv
    **kwargs)
  File "/usr/lib/python3.5/configparser.py", line 800, in _get
    return conv(self.get(section, option, **kwargs))
  File "/usr/lib/python3.5/configparser.py", line 797, in get
    d)
  File "/usr/lib/python3.5/configparser.py", line 393, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/usr/lib/python3.5/configparser.py", line 410, in _interpolate_some
    p = rest.find("%")
AttributeError: 'int' object has no attribute 'find'
```

**Comment by durera** [comment]
Will get an 0.3.3 release out shortly that resolves this 👍
